### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [dtutic/CartoLineGen#1]
There are other plugins doing an apparently similar analysis (e.g. v.generalize in Processing/GRASS and Generalizer plugin).
Please explain the need of another one.
In case this adds significant functionality, please consider merging your work with that of others.
Rationale: we try hard to reduce duplication, to make life of developer easier, and reduce the confusion for users.

**Comment by dtutic** [comment]
Dear Paolo,

thank you on your question and suggestion. I am well aware of v.generalize
module. My first implementation of our approach was in GRASS based on this
module (http://www.kartografija.hr/gshhs/). Then (2011) it was published
over WPS, but it proved that only few professional were/are aware of and
use WPS-clients. Implementation was also cumbersome because the WPS server
and client software was in early and unstable stages. Few weeks ago after
OS update on my server it again stopped working and I have to fix it
again.

Few weeks ago I was on ICA Mountain Cartography Workshop where I presented
our approach to cartographic line generalisation (I stress the word
cartographic because lot of existing algorithms are kind of filtering
algorithms, which is good to save space on disk or speed up processing,
but not for map production). Map makers see the potential of use of our
approach and they asked for QGIS plugin since most of them know how to
work in QGIS.

You can find the presentation attached, where all good and bad points of
our approach are given.

In 10 and more years I was never able to utilize v.generalize in order to
get generalized lines more or less ready for final map. I tried this
morning again and after 1 hour of trial I quit. v.generalize is just too
complicated, hard to understand and use (and I am quite familiar with line
generalization since I teach it), you need at least three separate steps
(simplification, smoothing and area filtering) with many trials of
different parameters, and the result is still not satisfactory from the
cartographic point of view.

With our approach you just need to zoom the map to scale you want to
generalize, and run plugin. It is based on several years of research of
manual line generalization.

This implementation has its drawbacks, e.g. speed, for it is in python,
but if community finds it useful I will be glad to work on its
improvements (first implementation was in C).

I am not in any way insisting on inclusion to official repository, I can
share link on GitHub to interested professionals, but on the other hand if
you search for "generalis(z)ation" in plugins there are no results for
now.

Inclusion of our approach in v.generalize would just make things even more
complicated for users.

Sorry for long mail. And last, these two plugins is all I plan to
contribute to already really great QGIS, for these two are fields of my
expertise. Unfortunately map projections and cartographic generalization
is something that regular GIS users often are not aware of, and it is not
uncommon that results and visualizations of GIS analysis are poor even
though they are made with state of the art technology.

Kind regards
Dražen Tutić

**Comment by pcav** [comment]
Quite convincing, thanks. Could you please add an abstract of your consideration to the About, so users are aware of it?
Now publishing it.

**Comment by dtutic** [comment]
I have updated about section and uploaded version which should work and be usable.
